export const FETCH_TASKS = 'FETCH_TASKS'
export const TASK_ADD = 'TASK_ADD'
export const TASK_DELETE = 'TASK_DELETE'
export const TASKS_DELETE = 'TASKS_DELETE'
export const TASK_DONE = 'TASK_DONE'
export const task = 'task'