export const FETCH_USERS = 'FETCH_USERS'
export const REMOVE_USERS = 'REMOVE_USERS'
export const USER_ADD = 'USER_ADD'
export const USER_EDIT_USERS = 'USER_EDIT_USERS'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_REMOVE = 'USER_REMOVE'
export const user = 'user'